; Example of settings file for CARLA.
;
; This file can be loaded with the Python client to be sent to the server. It
; defines the parameters to be used when requesting a new episode.
;
; Note that server specific variables are only loaded when launching the
; simulator. Use it with `./CarlaUE4.sh -carla-settings=Path/To/This/File`.

[CARLA/Server]
UseNetworking=false
WorldPort=2000
ServerTimeOut=1
SynchronousMode=false
SendNonPlayerAgentsInfo=false

[CARLA/QualitySettings]
; Quality level of the graphics, a lower level makes the simulation run
; considerably faster. Available: Low or Epic.
QualityLevel=Epic
; anything that's not WxH[w|f] will have no effect and keep the command line settings
Resolution=false

[CARLA/LevelSettings]
PlayerVehicle=
NumberOfVehicles=10
NumberOfPedestrians=64
WeatherId=1
; Seeds for the pseudo-random number generators.
SeedVehicles=123456789
SeedPedestrians=123456789
DisableTwoWheeledVehicles=true

[CARLA/Sensor]
;Sensors=EffectsCam/SemSeg

[CARLA/Sensor/EffectsCam]
SensorType=CAMERA
; Post-processing effect to be applied to this camera. Valid values:
;   * None                  No effects applied.
;   * SceneFinal            Post-processing present at scene (bloom, fog, etc).
;   * Depth                 Depth map ground-truth only.
;   * SemanticSegmentation  Semantic segmentation ground-truth only.
PostProcessing=SceneFinal
; Size of the captured image in pixels.
ImageSizeX=320
ImageSizeY=240
; Camera (horizontal) field of view in degrees.
FOV=100
; Position of the camera relative to the car in meters.
PositionX=1.60
PositionY=0
PositionZ=1.20
; Rotation of the camera relative to the car in degrees.
RotationPitch=0
RotationRoll=0
RotationYaw=0

[HUD]
ShowFPS=false
ShowNavigationInfo=false
ShowDebugInfo=false
ReticuleType=Multiply
ShowPoints=true

[fMRI]
; stuff for the navigation experiments
ExperimentType=Learning Practice List
SensorsOnlyOnReplay=true
AutoEyetrackingCalibration=false
Subject=None
RememberLocationBetweenSpawns=true
AutoTriggerDemoRecording=false
SecondsBeforeAISteering=0.0
ButtonBoxControls=false
SecondsToDemoStop=0
; limit players to speed limits?
governorOnPlayer=false

[NavigationExperiment]
Destinations=all
Proximity=400
ExclusionMin=12000
ExclusionMaxStart=35000
ExclusionMaxEnd=75000
ExclusionMinProbability=0.1
DestinationPickingMode=Pure Permuted
NavigationSequenceFile=default

[Foraging]
MinNumberTargets=70
MaxNumberTargets=77
AvailableTargetMultiplier=2.5
LowValuePoints=10
MedValuePoints=20
HighValuePoints=40
BaseTrialTime=90
AdditionalItemTime=15
MinStableTrials=3
ValueResetProbability=0.33

[LearningPractice]
DestinationPoints=true

[Controls]
HelpButtonActive=true

[Traffic]
; stuff for making cars biased to go towards the subject

; max probability that vehicles should be sent in direct towards the subject
maxSubjectBias = 0.9

;amount to direct away from subject in inversion
repulsionBias = 0.55

; distance from subject at which cars begin to be directed directed _away_ from subject
inversionRadius = 10000

; distance from subject at which max attraction begins
maxBiasRadius = 60000

; distance from subject at which max repulsion is reached
minBiasRadius = 7500

; default speed limit
defaultSpeedLimit = 35.0

; time spent at no movement at which an AI car will be despawned and respawned elsewhere
reincarnation = 15.0
;Duration between respawns of vehicles
respawnInterval = 0.5
; Min distance in meters to spawn vehicle from subject
minSpawnDistance = 25.0
; Max distance in meters to spawn vehicle from subject
maxSpawnDistance = 100.0
; number of seconds the spawn point must be from the subject given the subject's current speed
minTimeFromPlayer = 10.0

maxSpawnAngle= 120.0
offScreenLiveTime = 20.0
numberToRespawnInOneGo = 3

lowTrafficNumberOfVehicles = 10
lowTrafficMinSpawnDistance = 75.0
lowTrafficMaxSpawnDistance = 0.0

highTrafficNumberOfVehicles = 40
highTrafficMinSpawnDistance = 30.0
highTrafficMaxSpawnDistance = 0.0